stages:
  - source
  - build
  - appimage
  - build-dev
  - publish
  - release

source:
  stage: source
  needs: []
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
  image: denoland/deno:ubuntu
  before_script:
    - apt-get update
    - apt-get install -y curl rsync zstd
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION source
  artifacts:
    paths:
      - .dist/*.source.tar.zst

build:
  stage: build
  needs:
    - job: source
      artifacts: true
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
        PLATFORM: [linux, macos]
        ARCH: [x64, aarch64]
      - EDITION: [dr640nized, catppuccin]
        PLATFORM: windows
        ARCH: x64
  image: denoland/deno:ubuntu
  before_script:
    - apt-get update
    - apt-get install -y zstd python3-pip msitools
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION --target=$PLATFORM-$ARCH --enable-bootstrap build
  artifacts:
    paths:
      - .dist/*.$PLATFORM-$ARCH.*

appimage:
  stage: appimage
  needs:
    - job: build
      artifacts: true
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
        PLATFORM: linux
        ARCH: [x64, aarch64]
  variables:
    APPIMAGE_EXTRACT_AND_RUN: 1
  image: denoland/deno:ubuntu
  before_script:
    - apt-get update
    - apt-get install -y zstd
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION --target=$PLATFORM-$ARCH appimage
  artifacts:
    paths:
      - .dist/*.appimage-$ARCH.AppImage

build-dev:
  stage: build-dev
  needs: []
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
        PLATFORM: [linux, macos]
        ARCH: [x64, aarch64]
      - EDITION: [dr640nized, catppuccin]
        PLATFORM: windows
        ARCH: x64
  image: denoland/deno:ubuntu
  before_script:
    - apt-get update
    - apt-get install -y curl rsync zstd python3-pip msitools
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION --target=$PLATFORM-$ARCH --enable-bootstrap build-dev
  artifacts:
    paths:
      - .dist/*.$PLATFORM-$ARCH.dev.tar.zst

publish:
  stage: publish
  needs:
    - job: source
      artifacts: true
    - job: build
      artifacts: true
    - job: appimage
      artifacts: true
    - job: build-dev
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.source.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.source.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-x64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-aarch64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-aarch64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.windows-x64.zip" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.windows-x64.zip"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.macos-x64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-x64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.macos-aarch64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-aarch64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.appimage-x64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-x64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.appimage-aarch64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-aarch64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-x64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.windows-x64.dev.zip" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.windows-x64.dev.zip"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.macos-x64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-x64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-aarch64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-aarch64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst"'

release:
  stage: release
  needs:
    - job: publish
      artifacts: false
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm git-cliff release-cli
  script:
    - |
      release-cli create --tag-name "$CI_COMMIT_TAG" --name "FireDragon $CI_COMMIT_TAG" --description "$(git-cliff --current -s header)" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.windows-x64.zip\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.macos-x64.dev.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.macos-x64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-x64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.zip\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-aarch64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-aarch64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.dev.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.windows-x64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-x64.dev.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-x64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.macos-aarch64.dev.tar.zst\",\"link_type\":\"package\"}"
