stages:
  - source
  - build
  - appimage
  - build-dev
  - publish
  - release

source:
  stage: source
  needs: []
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm deno rsync
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION source
  artifacts:
    paths:
      - .dist/*.source.tar.zst

build:
  stage: build
  needs:
    - job: source
      artifacts: true
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm deno rsync python clang mold llvm alsa-lib jack libpulse rust cbindgen nodejs gtk3 unzip nasm wasi-compiler-rt wasi-libc wasi-libc++ wasi-libc++abi lld dbus-glib libsm
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION build
  artifacts:
    paths:
      - .dist/*.linux-x86_64.tar.zst

appimage:
  stage: appimage
  needs:
    - job: build
      artifacts: true
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
  variables:
    APPIMAGE_EXTRACT_AND_RUN: 1
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm deno
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION appimage
  artifacts:
    paths:
      - .dist/*.appimage-x86_64.AppImage

build-dev:
  stage: build-dev
  needs: []
  parallel:
    matrix:
      - EDITION: [dr640nized, catppuccin]
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm deno rsync python clang mold llvm alsa-lib jack libpulse rust cbindgen nodejs gtk3 unzip nasm wasi-compiler-rt wasi-libc wasi-libc++ wasi-libc++abi lld dbus-glib libsm
    - deno install --allow-scripts --frozen
  script:
    - deno task make --edition=$EDITION build-dev
  artifacts:
    paths:
      - .dist/*.linux-x86_64.dev.tar.zst

publish:
  stage: publish
  needs:
    - job: source
      artifacts: true
    - job: build
      artifacts: true
    - job: appimage
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.source.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.source.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.appimage-x86_64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-x86_64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x86_64.AppImage" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x86_64.AppImage"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ".dist/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst"'

release:
  stage: release
  needs:
    - job: publish
      artifacts: false
  rules:
    - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/stefanwimmer128/archlinux-chaotic-paru-user:latest
  before_script:
    - paru -Syu --noconfirm git-cliff release-cli
  script:
    - |
      release-cli create --tag-name "$CI_COMMIT_TAG" --name "FireDragon $CI_COMMIT_TAG" --description "$(git-cliff --current -s header)" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.source.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"filepath\":\"/firedragon-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon/${CI_COMMIT_TAG##v}/firedragon-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.source.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.appimage-x86_64.AppImage\",\"link_type\":\"package\"}" \
        --assets-link "{\"name\":\"firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.tar.zst\",\"filepath\":\"/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst\",\"url\":\"$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/firedragon-catppuccin/${CI_COMMIT_TAG##v}/firedragon-catppuccin-$CI_COMMIT_TAG.linux-x86_64.dev.tar.zst\",\"link_type\":\"package\"}"
