name: Build for Linux x64

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Prepare build environment
        run: |
          mkdir -p .deno
          mkdir -p .mozbuild
          echo "dummy-date" > _dist/moz_build_date
          echo "dummy-buildid" > _dist/buildid2
          mkdir -p _dist

      - name: Run build
        env:
          DENO_DIR: ${{ github.workspace }}/.deno
          MOZBUILD_STATE_PATH: ${{ github.workspace }}/.mozbuild
        run: |
          deno task make --edition=dr460nized --target=linux-x64 --enable-bootstrap --with-moz-build-date=_dist/moz_build_date --with-buildid2=_dist/buildid2 --with-dist=_dist build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firedragon-linux-x64
          path: .dist/*-linux-x64.*
